name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: web
        run: npm ci

      - name: Build with Next.js
        working-directory: web
        env:
          NODE_ENV: 'production'
        run: |
          # Clean previous builds
          rm -rf .next out
          
          # Build the application
          npm run build
          
          # Export to static files
          npm run export
          
          # Create necessary directories
          mkdir -p out/_next/static
          
          # Copy static assets
          cp -r public/* out/
          
          # Copy build assets
          cp -r .next/static/* out/_next/static/
          
          # Create _next directory for static export
          mkdir -p out/_next/static/chunks/pages
          
          # Copy necessary JavaScript files
          for file in .next/static/chunks/*.js; do
            cp "$file" out/_next/static/chunks/
          done
          
          # Copy CSS files
          cp -r .next/static/css out/_next/static/
          
          # Create a simple 404.html for GitHub Pages
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/vibes_fm/404"></head></html>' > out/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web/out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'web-artifact'
          target_branch: gh-pages
          keep_history: true